subject:
  subject_id: pico
  date_of_birth: 2019-12-04 00:00:00-05:00
  sex: male
  species: Macaca mulatta
  weight: 0.02 kg
session_info:
  session_id: x
  session_description: 'Number of Repetitions: x'
paths:
  intandata: 
    /braintree/data2/active/users/sgouldin/projects/oasis900/monkeys/pico/intanraw/pico_oasis900_230509_114338
general:
  experiment_info:
    experiment_description: 'Task: Rapid serial visual presentation (RSVP). Trial:
      Try 8 images - x ms on, x ms grey buch check mworks file for specifics. Reward:s
      juice reward after every trial. Imageset: x Images of x'
    keywords:
    - Vistual Stimuli
    - Object Recognition
    - Inferior temporal cortex (IT)
    - Ventral visual pathway
    related_publications:
    - ''
    protocol: Rapid serial visual presentation (RSVP)
    surgery: 3x Utah Array Implant + Headpost
  lab_info:
    university: Massachusetts Institute of Technology
    institution: McGovern Institute for Brain Research
    lab: DiCarlo
    experimenter: Goulding, Sarah
hardware:
  electrode_name: Electrode
  electrode_description: Utah CerePort Array with a single electrode array
  electrode_manuf: 2020 Blackrock Microsystems, LLC
  system_name: RecordingSystem
  system_description: RHD Recording System
  system_manuf: 2010-2023 Intan Technologies
  adapter_name: Utah Array Pedestal Connector
  adapter_description: Connects Utah Pedestal to Intan RHD Recording System
  adapter_manuf: Ripple Neuro
  photodiode_name: DET36A2 Biased Si Detector
  photodiode_description: Photodiode for detecting image presentation times. Comes
    with DET2A Power Adapter
  photodiode_manuf: Thorlabs Inc.
  monitor_name: LG UltraGear
  monitor_description: LG 32GP850-B 32 UltraGear QHD (2560 x 1440) Nano IPS Gaming
    Monitor w/ 1ms (GtG) Response Time & 165Hz Refresh Rate.                        Manually
    color calibrated and set to 120 HZ refresh rate.
  monitor_manuf: LG
software:
  mwclient_version: Version 0.11 (2022.02.15)
  mwserver_version: Version 0.11 (2022.02.15)
  OS: macOS Monterery on MAC Pro (Late 2013)
  intan_version: Version 3.1.0
metadata:
  nwb_version: 2.6.0
  file_create_date: 2023-09-12 14:09:19.670169-04:00
  identifier: 85bbbacd-9d9f-45f3-b57e-1e9674a22bcc
  session_start_time: 2023-09-12 14:09:19.670343-04:00
array_info:
  intan_electrode_labeling_[row,col,id]: '[[8.0, 9.0, 18.0], [7.0, 8.0, 20.0], [7.0,
    9.0, 22.0], [6.0, 9.0, 24.0], [5.0, 9.0, 26.0], [4.0, 9.0, 28.0], [3.0, 9.0, 30.0],
    [2.0, 9.0, 32.0], [4.0, 8.0, 31.0], [5.0, 8.0, 29.0], [6.0, 8.0, 27.0], [6.0,
    7.0, 25.0], [7.0, 7.0, 23.0], [5.0, 7.0, 21.0], [6.0, 6.0, 19.0], [7.0, 5.0, 17.0],
    [6.0, 5.0, 15.0], [7.0, 6.0, 13.0], [8.0, 6.0, 11.0], [8.0, 5.0, 9.0], [8.0, 4.0,
    7.0], [7.0, 4.0, 5.0], [9.0, 3.0, 3.0], [9.0, 2.0, 1.0], [9.0, 1.0, 2.0], [9.0,
    4.0, 4.0], [9.0, 5.0, 6.0], [9.0, 6.0, 8.0], [9.0, 7.0, 10.0], [8.0, 7.0, 12.0],
    [9.0, 8.0, 14.0], [8.0, 8.0, 16.0], [5.0, 5.0, 18.0], [4.0, 6.0, 20.0], [5.0,
    6.0, 22.0], [3.0, 5.0, 24.0], [3.0, 6.0, 26.0], [3.0, 7.0, 28.0], [4.0, 7.0, 30.0],
    [3.0, 8.0, 32.0], [1.0, 8.0, 31.0], [2.0, 8.0, 29.0], [2.0, 7.0, 27.0], [2.0,
    6.0, 25.0], [2.0, 5.0, 23.0], [2.0, 4.0, 21.0], [3.0, 4.0, 19.0], [2.0, 3.0, 17.0],
    [3.0, 3.0, 15.0], [3.0, 2.0, 13.0], [4.0, 3.0, 11.0], [4.0, 2.0, 9.0], [5.0, 2.0,
    7.0], [6.0, 2.0, 5.0], [7.0, 2.0, 3.0], [8.0, 2.0, 1.0], [8.0, 3.0, 2.0], [7.0,
    3.0, 4.0], [6.0, 3.0, 6.0], [5.0, 3.0, 8.0], [5.0, 4.0, 10.0], [4.0, 4.0, 12.0],
    [4.0, 5.0, 14.0], [6.0, 4.0, 16.0], [2.0, 2.0, 18.0], [1.0, 2.0, 20.0], [1.0,
    3.0, 22.0], [0.0, 4.0, 24.0], [0.0, 5.0, 26.0], [0.0, 6.0, 28.0], [1.0, 7.0, 30.0],
    [0.0, 8.0, 32.0], [1.0, 9.0, 31.0], [0.0, 7.0, 29.0], [1.0, 6.0, 27.0], [1.0,
    5.0, 25.0], [1.0, 4.0, 23.0], [0.0, 3.0, 21.0], [0.0, 2.0, 19.0], [0.0, 1.0, 17.0],
    [1.0, 0.0, 15.0], [2.0, 0.0, 13.0], [3.0, 0.0, 11.0], [4.0, 0.0, 9.0], [5.0, 0.0,
    7.0], [6.0, 0.0, 5.0], [7.0, 0.0, 3.0], [8.0, 0.0, 1.0], [8.0, 1.0, 2.0], [7.0,
    1.0, 4.0], [6.0, 1.0, 6.0], [5.0, 1.0, 8.0], [4.0, 1.0, 10.0], [3.0, 1.0, 12.0],
    [2.0, 1.0, 14.0], [1.0, 1.0, 16.0], [8.0, 9.0, 18.0], [7.0, 8.0, 20.0], [7.0,
    9.0, 22.0], [6.0, 9.0, 24.0], [5.0, 9.0, 26.0], [4.0, 9.0, 28.0], [3.0, 9.0, 30.0],
    [2.0, 9.0, 32.0], [4.0, 8.0, 31.0], [5.0, 8.0, 29.0], [6.0, 8.0, 27.0], [6.0,
    7.0, 25.0], [7.0, 7.0, 23.0], [5.0, 7.0, 21.0], [6.0, 6.0, 19.0], [7.0, 5.0, 17.0],
    [6.0, 5.0, 15.0], [7.0, 6.0, 13.0], [8.0, 6.0, 11.0], [8.0, 5.0, 9.0], [8.0, 4.0,
    7.0], [7.0, 4.0, 5.0], [9.0, 3.0, 3.0], [9.0, 2.0, 1.0], [9.0, 1.0, 2.0], [9.0,
    4.0, 4.0], [9.0, 5.0, 6.0], [9.0, 6.0, 8.0], [9.0, 7.0, 10.0], [8.0, 7.0, 12.0],
    [9.0, 8.0, 14.0], [8.0, 8.0, 16.0], [5.0, 5.0, 18.0], [4.0, 6.0, 20.0], [5.0,
    6.0, 22.0], [3.0, 5.0, 24.0], [3.0, 6.0, 26.0], [3.0, 7.0, 28.0], [4.0, 7.0, 30.0],
    [3.0, 8.0, 32.0], [1.0, 8.0, 31.0], [2.0, 8.0, 29.0], [2.0, 7.0, 27.0], [2.0,
    6.0, 25.0], [2.0, 5.0, 23.0], [2.0, 4.0, 21.0], [3.0, 4.0, 19.0], [2.0, 3.0, 17.0],
    [3.0, 3.0, 15.0], [3.0, 2.0, 13.0], [4.0, 3.0, 11.0], [4.0, 2.0, 9.0], [5.0, 2.0,
    7.0], [6.0, 2.0, 5.0], [7.0, 2.0, 3.0], [8.0, 2.0, 1.0], [8.0, 3.0, 2.0], [7.0,
    3.0, 4.0], [6.0, 3.0, 6.0], [5.0, 3.0, 8.0], [5.0, 4.0, 10.0], [4.0, 4.0, 12.0],
    [4.0, 5.0, 14.0], [6.0, 4.0, 16.0], [2.0, 2.0, 18.0], [1.0, 2.0, 20.0], [1.0,
    3.0, 22.0], [0.0, 4.0, 24.0], [0.0, 5.0, 26.0], [0.0, 6.0, 28.0], [1.0, 7.0, 30.0],
    [0.0, 8.0, 32.0], [1.0, 9.0, 31.0], [0.0, 7.0, 29.0], [1.0, 6.0, 27.0], [1.0,
    5.0, 25.0], [1.0, 4.0, 23.0], [0.0, 3.0, 21.0], [0.0, 2.0, 19.0], [0.0, 1.0, 17.0],
    [1.0, 0.0, 15.0], [2.0, 0.0, 13.0], [3.0, 0.0, 11.0], [4.0, 0.0, 9.0], [5.0, 0.0,
    7.0], [6.0, 0.0, 5.0], [7.0, 0.0, 3.0], [8.0, 0.0, 1.0], [8.0, 1.0, 2.0], [7.0,
    1.0, 4.0], [6.0, 1.0, 6.0], [5.0, 1.0, 8.0], [4.0, 1.0, 10.0], [3.0, 1.0, 12.0],
    [2.0, 1.0, 14.0], [1.0, 1.0, 16.0]]'
  array_A:
    position:
    - 0.0
    - 0.0
    - 0.0
    serialnumber: 6250-002929
    adapterversion: adaptorAIT.v2.2023
    hemisphere: L
    region: IT
    subregion: aIT
  array_B:
    position:
    - 0.0
    - 0.0
    - 0.0
    serialnumber: 6250-002929
    adapterversion: adaptorAIT.v2.2023
    hemisphere: L
    region: IT
    subregion: aIT
  array_C:
    position:
    - 0.0
    - 0.0
    - 0.0
    serialnumber: 6250-002929
    adapterversion: adaptorAIT.v2.2023
    hemisphere: L
    region: IT
    subregion: aIT
  array_D:
    position:
    - 0.0
    - 0.0
    - 0.0
    serialnumber: 6250-002933
    adapterversion: adaptorPIT.v2.2023
    hemisphere: L
    region: IT
    subregion: pIT
  array_E:
    position:
    - 0.0
    - 0.0
    - 0.0
    serialnumber: 6250-002933
    adapterversion: adaptorPIT.v2.2023
    hemisphere: L
    region: IT
    subregion: pIT
  array_F:
    position:
    - 0.0
    - 0.0
    - 0.0
    serialnumber: 6250-002933
    adapterversion: adaptorPIT.v2.2023
    hemisphere: L
    region: IT
    subregion: pIT
